version: "3.8"

services:
  vpn_telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vpn_telegram_bot
    env_file:
      - .env
    volumes:
      # База данных SQLite
      - ./data:/app/data

      # Логи
      - ./logs:/app/logs

      # Статика (если понадобится)
      - ./static:/app/static
    restart: unless-stopped
